[build]
    publish = "public"

[build.environment]
    HUGO_VERSION = "0.100.2"
    HUGO_THEME = "repo"

[[plugins]]
    package = "netlify-plugin-hugo-cache-resources"

        [plugins.inputs]
            # If it should show more verbose logs (optional, default = true)
            debug = true
            # Relative path to source directory in case you use Hugo's "--s" option
            srcdir = "exampleSite"
